# Generated by Django 2.0.7 on 2020-11-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermobdata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermobdata',
            name='username',
            field=models.CharField(default='no name', max_length=50),
        ),
    ]
