# Generated by Django 2.0.7 on 2020-11-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('medicine_name', models.CharField(max_length=100)),
                ('batch_id', models.CharField(max_length=50)),
                ('mfd', models.DateField()),
                ('number_of_boxes', models.IntegerField()),
                ('exd', models.DateField()),
                ('invoice_no', models.CharField(max_length=50)),
                ('no_of_pieces', models.IntegerField()),
                ('date_of_purchase', models.DateField()),
                ('date_of_added', models.DateTimeField()),
            ],
        ),
    ]
