# Generated by Django 2.0.7 on 2020-11-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedata',
            name='no_of_days_left',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
