# Generated by Django 2.0.7 on 2020-11-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicinedata_no_of_days_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedata',
            name='no_of_days_left',
            field=models.IntegerField(default='0'),
        ),
    ]
