# Generated by Django 2.0.7 on 2020-11-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201112_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedata',
            name='no_of_days_left',
            field=models.IntegerField(default=0),
        ),
    ]
