# Generated by Django 2.0.7 on 2020-11-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201112_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedata',
            name='no_of_days_left',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
